### ISSUE TITLE
[Question] Correct way to implement higher order wrappers to add lifecycle methods to observers?

### ISSUE THREAD

**Issue by robstown** [mobxjs/mobx-react#271] opened 2017-06-06 20:11 UTC
What is the recommended way to create higher order functions to add react lifecycle methods to observer components?  For example, lets say I wanted to add a logger to some of my observers that logs to the console after an instance has updated.  I might write a wrapper as follows:

```
export var logger = (WrappedComponent) => {  
	return (
		class extends React.Component {
			componentDidUpdate(){
				console.log('componentDidUpdate')
			}
			render() {
				return (<WrappedComponent {...this.props}/>);
			}
		}
	);
};
```

If I try to add it to an observer component as follows, it never logs the update because only the inner component updates (wrapped component) using sideways loading and so the logger doesn't work:

```
@logger
@observer
class MyButton extends React.Component {
	render() {
		let {store, children, style, ...props} = this.props;
		style = {...{backgroundColor:store.bgColor}, ...style};	
		return (
			<div className='MyButton' style={style} onClick={store.onClick} {...props}>
				store.label
			</div>
		);
	}
}
```
If I try to put the `@logger` after the `@observer`, it will no longer reactively update.  Am I missing something?  Is there an effective way to generically add lifecycle events to reactive observers in a composable way.  I am trying to avoid mixins since they are being deprecated in future versions of react.

Thanks!

**Comment by robstown** [comment] 2017-06-07 04:19
Thanks @urugator, interesting approach.  Since the wrapped component will not react on it's own, I see I will need a passthrough for other updating methods, like `componentWillUpdate`, ie:

```
 componentWillUpdate() {
    WrappedComponent.prototype.componentWillUpdate.call(this);
 }
```
If I don't and I define such a function in the wrapped component, it won't execute.  The mount methods seems to work regardless.

Thanks again, you are always helpful!!!

**Comment by urugator** [comment] 2017-06-07 10:38
> If I don't and I define such a function in the wrapped component, it won't execute. 

It will, check the update codesandbox example. Notice that the new component `extends` from the wrapped, therefore if some method is not defined on the wrapper, it's call is automatically delegated through prototype chain to the original component. You have to deleagte the call manually only if you overwrite the method.
Btw you can call just `super.componentWillUpdate()` (it desugars to the same cal)

**Comment by mweststrate** [comment] 2017-06-13 08:46
Closing, question is answered.

**Closed by mweststrate** 2017-06-13 08:46 UTC

**Comment by healthycola** [comment] 2018-03-05 21:00
Thank you for your answer @urugator. Is inheritance the only way go about doing this? React has all these warnings and flags for avoiding inheritance, and using composition, but I can't see any other way to get around this. Am I missing anything or this is the only way?

**Comment by urugator** [comment] 2018-03-06 11:08
> componentWillReact for a HOC to get updates?

Same situation as with `componentWillUpdate` just limited to updates caused by observables. When parent updates/reacts it doesn't mean that children will update/react as well and vice versa.
Whats your use case?

**Comment by goldylucks** [comment] 2019-07-24 06:40
@urugator your solution works for me without the `componentDidUpdate` call. It also crashes btw, it's undefined (maybe react did some internal changes since)
