### ISSUE TITLE
Component alway re-render with no state update when using @withRouter (RR4)

### ISSUE THREAD

**Issue by ollydbgz** [mobxjs/mobx-react#296] opened 2017-07-07 04:32 UTC
I'm using MobX @observer and @withRouter (react-router-v4) wrap page component like this
    
    @withRouter
    @inject('stores')
    @observer
    class Page extends Component {
      render() {
        return (
          <div>
            <NavBar />
            <Header title={this.props.stores.UIStore.title} />
            <Switch>
              <Route exact path="/" component={HomePage} />
              <Route exact path="/about" component={AboutPage} />
              <Route component={NotFound} />
            </Switch>
          </div>
        )
      }
**Problem**  
When route location change the NavBar and Header component alway re-render with same props (no any state update). react-perf show many wasted render (no props/state update) when route change.

NavBar include Link and some MobX state (NavBar wrap with @observer+@inject only)
Header is just a stateless component

How to prevent NavBar and Header re-render from route location change? Allow re-render only when mobx state update.

**Comment by mweststrate** [comment] 2017-07-07 07:50
Duplicate of #274 ? Note that you probably should swap `withRouter` and `inject`

**Comment by ollydbgz** [comment] 2017-07-07 08:22
I have also swap @withRouter/@inject but there are still problems. Component trigger wasted re-render with previous props/state.

**Comment by mweststrate** [comment] 2017-07-11 12:53
@ollydbgz could you setup a small repo to demonstrate the problem, so we can investigate an optimal solution? Tnx!

**Comment by vstlouis** [comment] 2017-07-12 13:47
Ill try to get something up this week with an example if he doesn't get to it. It's been a struggle and I can verify that I needed to have my withRouter HoC on the outside.

**Comment by MovingGifts** [comment] 2017-07-27 15:04
@ollydbgz @vstlouis Did you guys find a solution yet?

**Comment by dmitryk-dk** [comment] 2017-10-16 07:24
Hi guys! I have the same problem. And i create a sample app with this problem, you can check it here https://github.com/dmitryk-dk/stagram. When you click in heart it must increment, but it increment just when update the router.
Any idea about this issue @mweststrate ?

**Comment by mweststrate** [comment] 2017-11-28 19:32
Closing for the lack of a reproduction. People regularly complain about the interoperability between RR and mobx-react. So if the next one running into this would do the favor to create a minimal repro, we could *actually* look into this.  #ktnxbye

**Closed by mweststrate** 2017-11-28 19:32 UTC

**Comment by chbdetta** [comment] 2017-11-30 09:02
I think this is the expected behavior and has nothing to do with mobx? RR will trigger a `setState` at `<Router>` component when the location change, so the whole component tree will update. If you want to eliminate the wasted updates, you should consider `PureComponent`  or implement your own `shouldComponentUpdate`.

**Comment by johnnyreilly** [comment] 2018-01-09 10:17
> Duplicate of #274 ? Note that you probably should swap `withRouter` and `inject`

Hey @mweststrate,

My colleague @ryanand26 just had to switch `withRouter` to be the outermost call **instead** of `inject` as you suggested above.  I understand from him that without having `withRouter` as the outermost component, mobx components were not re-rendering upon url changes.

We've consulted the documentation on react-router here: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md#shouldcomponentupdate

It suggests that `withRouter` should be the outermost function call; contrary to what you've said here.  Can you confirm that we're correct on this?  Is there a reason `inject` should be the outermost rather than `withRouter`?

**Comment by uhoh-itsmaciek** [comment] 2018-09-30 10:45
>My colleague @ryanand26 just had to switch withRouter to be the outermost call instead of inject as you suggested above. I understand from him that without having withRouter as the outermost component, mobx components were not re-rendering upon url changes.

Do you have a reproduction of this? Doesn't `@inject` just pass stores to your components? Given that the stores themselves aren't changing, it doesn't seem like you'd need to re-apply the injection when routing changes.
