### ISSUE TITLE
Mobx not working with next.js properly 

### ISSUE THREAD

**Issue by ArtyomPLAY** [mobxjs/mobx-react#776] opened 2019-09-09 00:01 UTC
It just doesn't rerender component on state change. Tried everything, nothing works, while using pure React everything works fine. Any advices? Is there new(2019) examples for next.js + mobx integration ?

**Comment by FredyC** [comment] 2019-09-09 06:57
Possible duplicate of https://github.com/mobxjs/mobx-react-lite/issues/71, but it was never properly resolved. If you are keeping your state in global variables, it might be a problem due to concurrency of Next, but otherwise without a reproduction hard to say what's wrong in your case.

**Comment by ArtyomPLAY** [comment] 2019-09-09 20:50
@FredyC Thanks for answer.
I did get it work by getting decorator syntax in my project. Idk how it actually helps, but it works now, and im happy !)

**Closed** 2019-09-09 20:52 UTC
Labels: needs reproduction
