### ISSUE TITLE
Attempted to assign readonly property

### ISSUE THREAD

**Issue by aksonov** [mobxjs/mobx-react#99] opened 2016-08-04 10:01 UTC
3.5.1 version works fine, but 3.5.3 throws error when i'm wrapping React component using 

```
const component = this.props.component;
const wrapped = observer(component);
```

![simulator screen shot 04 aug 2016 11 58 55](https://cloud.githubusercontent.com/assets/1321329/17398016/f36d61d4-5a3a-11e6-97e9-2fbe6b77ccc0.png)

**Comment by mweststrate** [comment] 2016-08-04 17:44
nasty! some questions, is there a hot reloader active and does disabling
make a difference? does the wrapped component use decorators? and which
mobx version?

Op do 4 aug. 2016 12:01 schreef Pavel Aksonov <notifications@github.com>:

**Comment by aksonov** [comment] 2016-08-04 19:14
No hot reload. Probably yes, some decorators are exist.

Pavel.

**Comment by mweststrate** [comment] 2016-08-04 19:18
Does it make a difference if you don't use the decorators but functions instead? `@observer class` -> `observer(class ...`, `@observable` / `@computed` -> `extendObservable`. Which one is the culprit, if any? Make sure to be on the latest version of MobX, a possibly related issue was fixed recently

**Comment by aksonov** [comment] 2016-08-05 06:54
react-native-mobx using latest Mobx and observer() function to wrap all scenes automatically. Looks like latest react/mobx mutates param of observer function somehow, so React throws exception. Previous version didn't mutate it.

**Comment by mweststrate** [comment] 2016-08-05 06:55
Are you using inject or observers that are connected to stores
(observer([x,y], component)? If you can produce a less obfuscated
stacktrace that would be great!

Op vr 5 aug. 2016 om 08:54 schreef Pavel Aksonov <notifications@github.com>:

**Comment by aksonov** [comment] 2016-08-05 06:58
second, observer(component). Strange, it is just debug run on simulator (RN 0.30.0), i don't understand why React obfuscate it...

**Comment by aksonov** [comment] 2016-08-05 07:05
I meant 'u' and 's' sources. last 'iterate' is function of react-native-mobx, where observer(component) is called.

**Comment by aksonov** [comment] 2016-08-05 07:06
I have quite urgent task so i'm just using old version for a while. Will try to post more details here when i have time.

**Comment by andykog** [comment] 2016-08-05 09:52
```
const component = this.props.component;
const wrapped = observer(component);
```
@aksonov, This works fine in my react-native setup. I've also checked using Provider, `@inject`, `@observer` (both as decorators and as functions).
Could you enable remote debugging and get the exact place where the exception occurs?
Any help in reproducing this will be appreciated.

**Comment by mweststrate** [comment] 2016-08-11 18:48
Could this be a duplicate of #101 @aksonov ?

**Comment by mweststrate** [comment] 2016-08-12 19:20
@aksonov would you mind checking whether `3.5.5` solves this issue?

**Comment by aksonov** [comment] 2016-08-16 10:58
Unfortunately no.

**Comment by mweststrate** [comment] 2016-11-07 19:05
@aksonov ok to close this issue? I guess it is not urgent anymore after two months ;-). Otherwise please provide a reproduction :)

**Comment by aksonov** [comment] 2016-11-10 18:39
Just found that latest 3.6.2 solves issue, thanks!

**Closed** 2016-11-10 19:02 UTC
