### ISSUE TITLE
Using observer with react hooks does not work

### ISSUE THREAD

**Issue by barbalex** [mobxjs/mobx-react#594] opened 2018-10-31 11:30 UTC
https://codesandbox.io/s/7z9yok8mn1

This error occurs:
```
Hooks can only be called inside the body of a function component.
```

There is already an issue for this (https://github.com/mobxjs/mobx-react/issues/591) but it was closed as the author wants to wait for a version of mobx-react that uses hooks itself.

Although I am also looking forward to that my intention is to try out hooks in my projects and start using them, even if mobx-react itself can not yet be switched.

This is not possible as observer causes the above error.

**Comment by barbalex** [comment] 2018-10-31 13:11
looking at the code I get the feeling that observer is converting a function component to a class which will not work when using hooks?

**Comment by barbalex** [comment] 2018-10-31 13:14
So I guess we will have to wait for https://github.com/mobxjs/mobx-react/issues/588 to be able to use hooks together with mobx.

**Comment by johot** [comment] 2018-10-31 14:39
I have a working prototype now that fixes the error you are seeing (see #588). https://github.com/johot/mobx-react

**Comment by mweststrate** [comment] 2018-11-06 12:11
Closing in favor of #588. We won't be actively supporting a feature that is not actually released.

**Comment by mweststrate** [comment] 2018-11-06 12:12
The simple work around is to use `<Observer>` sections in your fucntion components, instead of `observer` wrapper around it

**Closed by mweststrate** 2018-11-06 12:11 UTC

**Comment by barbalex** [comment] 2018-11-06 12:29
@mweststrate I did not know about `<Observer>`. Thanks for the tip.

**Comment by davidtran** [comment] 2019-01-11 08:03
Please give me an example.

**Comment by mweststrate** [comment] 2019-01-11 08:09
See also mobx-react-lite package if you want to use hooks

Op vr 11 jan. 2019 09:03 schreef David Tran <notifications@github.com>:

**Comment by mweststrate** [comment] 2019-01-22 15:57
@davidtran `observer((props) => rendering)` is the same as `(props) => <Observer>{() => rendering}</Observer>`, but the latter has the benefit that it doesn't turn your function component into a class component.

**Comment by barbalex** [comment] 2019-01-22 16:01
You can now also use `observer` from [mobx-react-lite](https://github.com/mobxjs/mobx-react-lite#observer)

**Comment by ali-master** [comment] 2019-05-14 06:04
Hi guys.

I did your tips but the problem is still yet. May someone help me to fix it?
I'm using the latest version of React and mobx and the class way of mobx for managing stores and when I call an action function, everything looks good and the store will be updated but DOM can't update.

Thank you in advance and I appreciate your help.

**Comment by mweststrate** [comment] 2019-05-16 19:30
@ali-master please open a fresh issue, following the normal format with reproduction and such.

**Comment by ali-master** [comment] 2019-05-16 19:34
Thank you, I will
