### ISSUE TITLE
@inject('store') breaks hot reloading

### ISSUE THREAD

**Issue by oozaa** [mobxjs/mobx-react#301] opened 2017-07-19 19:52 UTC
When I use @inject decorator my hot reloading breaks. My app picks up updates but instead of patching it, it unmounts entire tree and mounts it back with updated components so I lose components state. If I remove @inject('store') from my code, all components hot reloads correctly.

Code:
`
@inject('store')
@observer
export default class HomePage extends React.Component<props, {}> {....}
`

**Comment by mweststrate** [comment] 2017-07-25 13:35
Which version of HMR?

**Comment by mweststrate** [comment] 2017-08-01 20:43
Note that only HMR `@next` version has (some) support for decorators. Personaly I don't trust HMR at all so usually I don't use it (everything becomes just to unpredictable imho) and development seems to have stopped. But here is a project that might serve as inspiration: https://github.com/mobxjs/react-mobx-boilerplate or https://github.com/mobxjs/mobx-reactive2015-demo

Also note that you don't need decorators for the above, `export default const HomePage = inject('store')(observer(class HomePage ... {}))` achieves the same

**Comment by oozaa** [comment] 2017-08-01 22:49
The version I have is - "react-hot-loader": "^3.0.0-beta.7"
Will try to use inject() the way you suggest. Thank you.

**Comment by scinos** [comment] 2017-08-23 11:52
I get this problem too. I don't think it is related to the usage of decorators, but to `observer()`:

This works:
```
const MainApp = () => (
  <span>1234</span>
);
```

This does not work:
```
const MainApp = observer(({ something }) => (
  <span>1234</span>
));
```

To be clear, by "works" I mean that the component is actually changed on the screen when I change the text `1234`. In *both* cases I get log output that suggest HMR is working:

```
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
> MobX Provider: Provided store 'actions' has changed. Please avoid replacing stores as the change might not propagate to all children
[...]
[HMR] Updated modules:
[HMR]  - ./views/MainApp/index.jsx
[HMR]  - ./main.jsx
[HMR] App is up to date.
```

I tested it with react-hot-loader 3.0.0-beta.6 and 3.0.0-beta.7.

**Comment by jackple** [comment] 2017-09-27 01:10
@scinos Have you solved this problem?

**Comment by mweststrate** [comment] 2017-09-27 07:44
Did you try `const MainAppImpl = () => <span/>; const MainApp =
observer(MainAppImpl)` ?

Op wo 27 sep. 2017 om 03:10 schreef jackple <notifications@github.com>:

**Comment by jackple** [comment] 2017-09-27 08:26
@mweststrate I tried to add listener to the file in stores, but every time I changed  one store in stores, the store will be a new one

**Comment by mweststrate** [comment] 2017-09-29 20:55
@jackpie. Hard to say anything useful in general, there are so many factors
in a setup that can be of influence.... Feel free to create a small(!)
reproduction and link it here :).

Op wo 27 sep. 2017 om 10:26 schreef jackple <notifications@github.com>:

**Comment by mweststrate** [comment] 2017-10-17 10:34
Closing for the lack of a test setup

**Closed by mweststrate** 2017-10-17 10:34 UTC

**Comment by tujoworker** [comment] 2017-10-30 20:27
Actually, React Hot Loader warns now as soon we use **inject** once a component change is going on. This warning comes up in the console. 

```javascript
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 ƒ Details() {
		_classCallCheck(this, Details);

		return _possibleConstructorReturn(this, (Details.__proto__ || Object.getPrototypeOf(Details)).apply(this, arguments));
	}
...
```

**Comment by yozi-developer** [comment] 2017-11-16 15:05
@mweststrate 

Look at this  https://github.com/yozi-developer/mobx-react-hmr

Any time I update `src/components/HotReload/Inner.tsx` I see:

>   React Hot Loader: this component is not accepted by Hot Loader.

**Comment by yozi-developer** [comment] 2017-11-17 13:47
Oh, it looks like problem with react-hot-loader, maybe with `react-hot-loader/webpack`. I've moved to awesome-typescript-loader+babel and hot reload works like a charm with `inject` now
