### ISSUE TITLE
TypeScript error when observer is used with a function that returns array of JSX elements

### ISSUE THREAD

**Issue by asfernandes** [mobxjs/mobx-react#365] opened 2017-11-21 16:26 UTC
```txt
mobx-react 4.3.4
```

```ts
export const Field = observer(function field(props: { key?: React.Key, label: string, children: React.ReactNode }) {
	return ([
		<label key="label">{`${props.label}:`}</label>,
		<div key="field" className="field">
			{props.children}
		</div>
	]);
});
```

```
Argument of type '(props: { key?: string | number | undefined; label: string; children: ReactNode; }) => Element[]' is not assignable to parameter of type 'IReactComponent<any>'.
  Type '(props: { key?: string | number | undefined; label: string; children: ReactNode; }) => Element[]' is not assignable to type 'ClassicComponentClass<any>'.
    Type '(props: { key?: string | number | undefined; label: string; children: ReactNode; }) => Element[]' provides no match for the signature 'new (props?: any, context?: any): ClassicComponent<any, ComponentState>'.
```

This one works:

```ts
export const Field = observer(function field(props: { key?: React.Key, label: string, children: React.ReactNode }) {
	return ([
		<label key="label">{`${props.label}:`}</label>,
		<div key="field" className="field">
			{props.children}
		</div>
	] as any);
});
```

**Comment by tjoskar** [comment] 2017-11-22 09:11
I have the same problem but I think the issue is within to the react type: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6cbca4ed13237f16533d400d18e15fe59eb2eac/types/react/index.d.ts#L322

**Comment by mweststrate** [comment] 2017-12-05 12:51
Is this an issue that needs addressing in the library. If so you could someone add a unit test to the typescript tests exposing this problem?

**Comment by mweststrate** [comment] 2018-02-05 14:29
Closing for lack of information

**Closed by mweststrate** 2018-02-05 14:29 UTC
