### ISSUE TITLE
Prop validation throws a warning when used on a decorated component expecting store

### ISSUE THREAD

**Issue by dmi-dmi-dmi** [mobxjs/mobx-react#70] opened 2016-06-23 20:23 UTC
When I run the code below I get `Warning: Failed propType: Required prop 'store' was not specified in 'MobXStoreInjector'. Check the render method of 'Root'` warning in the browser console.

```
import React, { Component, PropTypes } from 'react';
import ReactDOM from 'react-dom';
import { Provider, observer } from 'mobx-react';


const store = {};

@observer(['store']) class MyComponent extends Component {

  render() {
    return <div>abc</div>;
  }

}

MyComponent.propTypes = {
  store: PropTypes.object.isRequired,
};


function Root({ store }) {
  return (
    <Provider store={store}>
      <MyComponent />
    </Provider>
  );
}

ReactDOM.render(
    <Root store={store} />,
  document.getElementById('reactApp'));
```

**Comment by mweststrate** [comment] 2016-06-25 13:27
Quick question, do you use Typescript or Babel for transpiling?

**Comment by dmi-dmi-dmi** [comment] 2016-06-25 17:08
Babel 6

**Comment by jtraub** [comment] 2016-07-05 05:09
I've stumbled across this problem today.

As far as I understand it is not a bug at all.

If you read [decorator proposal](https://github.com/wycats/javascript-decorators) it will become clear that 

```
@observer(['store']) class MyComponent {
...
}
```
is equivalent to 

```
let MyComponent = (function () {
  class MyComponent {
  ...
  }
  
  return observer(['store])(MyComponent) || MyComponent
})();
```

At this line 
```
MyComponent.propTypes = {
``` 
we are attaching propTypes object to `MobXStoreInjector` instead of `MyComponent`. Hence, we get warning from React regarding required store prop: it doesn't receive such prop.

To confirm this let's inspect what Babel 6 without es2015 preset produces from the code in the first message:

```
import React, { Component, PropTypes } from 'react';
import ReactDOM from 'react-dom';
import { Provider, observer } from 'mobx-react';

const store = {};

let MyComponent = (_dec = observer(['store']), _dec(_class = class MyComponent extends Component {

  render() {
    return React.createElement(
      'div',
      null,
      'abc'
    );
  }

}) || _class);


MyComponent.propTypes = {
  store: PropTypes.object.isRequired
};

function Root({ store }) {
  return React.createElement(
    Provider,
    { store: store },
    React.createElement(MyComponent, null)
  );
}

ReactDOM.render(React.createElement(Root, { store: store }), document.getElementById('reactApp'));
```

I guess docs should be updated to articulate that you can not use `propTypes` with class decorators.

**Comment by jtraub** [comment] 2016-07-05 06:18
Solution could be addition of code which will be passing propTypes to decorated component.

Something like this

```
Object.defineProperty(Injector, 'propTypes', {
  set: function(val) {
    component.propTypes = val;
  }
});
```
[here](https://github.com/mobxjs/mobx-react/blob/master/index.js#L298).

I just did a quick hack and it seems to work for me. According to [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Browser_compatibility) `defineProperty` is not supported in really old browsers. Not sure if it matters here.

**Comment by jtraub** [comment] 2016-07-07 14:30
It seems that other HOCs do not pass `propTypes` to decorated components. People overcome this by defining `propTypes` as static property in component classes. [Random example](https://github.com/erikras/react-redux-universal-hot-example/blob/3e8453dba635c5792dc2ab61406bbe9545328b25/src/containers/App/App.js#L30).

Drawbacks of such approach:
1) it relies on stage-1 proposal (but decorators itself are stage-1 proposal)
2) `MyComponent.propTypes = ..` is considered to be an idiomatic way to work with `propTypes`. Style guides recommend doing it this way. See [Airbnb style guide](https://github.com/airbnb/javascript/tree/master/react#ordering) for example

**Comment by mweststrate** [comment] 2016-07-11 18:40
@dmi-dmi-dmi / @jtraub sorry for the late response, was searching for a while in the wrong direction for this. I think the simplest way to fix this is is to store the inner component in a temporarily var so that you can still access it:

```
class _MyComponent extends Component {

  render() {
    return <div>abc</div>;
  }

}

_MyComponent.propTypes = {
  store: PropTypes.object.isRequired,
};

const MyComponent = observer(['store'])(_MyComponent)
```

**Comment by mweststrate** [comment] 2016-07-11 19:11
Next release will introduce `inject` and `wrappedComponent` property, which would result in the following:

```javascript
@inject('store') @observer class MyComponent extends Component {
  render() {
    return <div>abc</div>;
  }
}

MyComponent.wrappedComponent.propTypes = {
  store: PropTypes.object.isRequired,
};
```

**Comment by mweststrate** [comment] 2016-07-11 20:39
Released as 3.5.0. Feel free to re-open if anything is unclear

**Closed** 2016-07-11 20:39 UTC

**Comment by mromanoff** [comment] 2016-10-21 00:48
@mweststrate i followed your last post on this topic. and still getting warning. 
**Mobx Injector: you are trying to attach propTypes to HOC instead of Actions. Use `wrappedComponent` property.**

here is my component:
```
@inject('providersStore') @observer
export default class Actions extends Component {
    render() {
        return <div>abc</div>;
    }
}

Actions.wrappedComponent.propTypes = {
  providersStore: PropTypes.object.isRequired
};

```
am i missing something?

**Comment by SagiMedina** [comment] 2016-10-31 07:10
@mromanoff did you find any solution to this warning?
@mweststrate ?
