### ISSUE TITLE
Better trace() logging for 'reactive state' and 'reactive props'

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx-react#599] opened 2018-10-25 17:44 UTC
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

3. [x] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

If feasible, I'll take a look. This would be a huge help for performance debugging generally.

Ideally, it would just show the "changed" props. For example right now I have a component where the props don't seem to change, yet it is updating.

**Comment by natew** [comment] 2018-11-15 17:30
For me this is actually more a request to *show the actual props* that changed for that reaction.

For me, I'm having a new render happen, but the props don't change. But mobx is still logging that there was a change in `reactive props`. Perhaps something weird is happening, but it's hard to debug *which* prop changed. So instead of:

```
[mobx.trace] 'SubPane#226.render()' is invalidated due to a change in: 'reactive props'
```

We could do:

```
[mobx.trace] 'SubPane#226.render()' is invalidated due to a change in: 'reactive props': ['propName']
```

Or something along those lines.

**Comment by mweststrate** [comment] 2019-03-14 11:02
This is probably caused by: https://github.com/mobxjs/mobx/issues/1803

**Comment by FredyC** [comment] 2020-04-22 16:46
Let's close it here since it doesn't seem to be troubling many people.

**Closed by FredyC** 2020-04-22 16:46 UTC
