### ISSUE TITLE
Typings on inject

### ISSUE THREAD

**Issue by tomitrescak** [mobxjs/mobx-react#323] opened 2017-09-11 08:21 UTC
Hi, the typings on inject are a bit off.
I have Component with props { foo: string };
Then I will perform mapping:

```ts
type ContainerProps = {
  bar: number
}
type ComponentProps = {
  foo: string
}

const Composed = inject<ComponentProps, ContainerProps>((stores, props) => 
    ({ foo: stores.some[props.bar]}))(Component);
```

The problem is that the returning component has props of type `ComponentProps`. so, when I try to use this component:

```js
<Composed bar={4}  />
```

I get error that `foo` parameter is missing. That's obviously incorrect, as the composed component should only receive `bar`.

**Comment by tomitrescak** [comment] 2017-09-11 09:04
Looking at the definition:

```ts
export function inject<P>(...stores: string[]): (<TFunction extends IReactComponent<P>>(target: TFunction) => (TFunction & IWrappedComponent<P>)); // decorator signature
export function inject<T, P>(storesToProps : IStoresToProps<T, P>): (<TFunction extends IReactComponent<T | P>>(target: TFunction) => (TFunction & IWrappedComponent<P>)); // decorator
```

This did the trick

```ts
export function inject<P>(...stores: string[]): (<TFunction extends IReactComponent<P>>(target: TFunction) => (IReactComponent<P>)); // decorator signature
export function inject<T, P>(storesToProps : IStoresToProps<T, P>): (<TFunction extends IReactComponent<T | P>>(target: TFunction) => (IReactComponent<P>)); // decorator
```

Not sure if it is what you meant, but in my opinion it is more correct. But I'm probably wrong here ;) What is the reasoning of the returning component also having props of the wrapped component?

**Comment by mweststrate** [comment] 2017-09-18 11:58
I think this is a duplicate of #256 ?

**Closed by mweststrate** 2017-09-18 11:58 UTC
