### ISSUE TITLE
Using a class instance with useLocalStore does not work

### ISSUE THREAD

**Issue by benvp** [mobxjs/mobx-react#722] opened 2019-07-01 13:15 UTC
I'm having two stores, `TodoStore` and a `RootStore`. The `TodoStores` get's a reference to the `RootStore` upon initialization. I am currently trying to use the React context and create a hook to use in my app. But when I create a new instance and pass it to the `useLocalStore` hook I only get an error: 

```
[mobx] The provided value could not be converted into an observable. If you want just create an observable reference to the object use 'observable.box(value)'
```

I am quite new to MobX, but when I spread into a new object using `{ ...new RootStore() }`, everything works just fine. Seems a bit confusing to me. I have created a codesandbox demonstrating the issue:

https://codesandbox.io/embed/stoic-sunset-7cewt

**Comment by FredyC** [comment] 2019-07-01 14:12
Upgrade to mobx-react 6 please.

**Comment by benvp** [comment] 2019-07-01 14:13
Well, I am actually running `mobx-react@6.1.1`

**Comment by FredyC** [comment] 2019-07-01 14:21
Sorry, was too quick with closing, looking closely at sandbox now, it might be actually a bug :) Perhaps even in `mobx` itself as we are basically just calling `mobx.observable` in that hook. I am pretty sure we wanted this use case to be possible, but I suppose never made into a test case and slipped. I will look into it later. Thanks!

**Comment by benvp** [comment] 2019-07-01 14:24
One additional information which *maybe* useful for investigation is, that as soon as you add one `@observable` property to the class, it works.

**Comment by FredyC** [comment] 2019-07-01 14:30
That's even weirder :) The `decorate` call shouldn't be there in the first place since we are running it through observable anyway.

I wonder, what do you actually expect from it? Don't worry about what's the advertised functionality, but what has convinced that you need to `useLocalStore` at all?

**Comment by benvp** [comment] 2019-07-01 14:35
As I said I am quite new to MobX in general and currently refactoring a project I have been assigned to. I was following the guide at https://mobx-react.js.org/recipes-context which says that I should use `useLocalState` to create a hook which let me access the store within react components. I am not a big fan of importing the store directly using a singleton.

Additionally I refactored the different stores to have one RootStore, which will create instances of the sub store and passing the instance of itself to the other stores. This is needed because the stores are currently referring to each other and I had to remove quite a few dependency cycles.

**Comment by FredyC** [comment] 2019-07-01 15:35
Ok, I remember now how we have intended this. The `useLocalStore` is not actually meant to support class-based state. To be precise, it's not supposed to crash there because of it. It should work like state keep only in that case. You can make yourself a simple custom hook to abstract it away.

```js
function useClassStore(init) {
  const [store] = React.useState(init)
  return store
}
// and then in a component
const store = useClassStore(() => new RootStore())
```

So in the end, it's not exactly a huge bug. We just need to properly check for a class instance before passing it to `observable` which cannot detect it properly.

---

Btw, why do you actually want class-based state? :) Do you see some actual benefit from it? The page you have linked shows how to do it directly with `useLocalStore`. I suppose you don't like that?

**Comment by benvp** [comment] 2019-07-01 17:28
Thanks for the workaround. Will try that also. Actually, the only reason is that the guy who implemented the stuff before used class-based state. I only did a bit refactoring to include a RootState for resolving the circular dependencies, which have been introduced by the different stores. 

When I find time for it, I'll refactor that to use plain objects and just have the dependant state as argument.

**Comment by FredyC** [comment] 2019-07-01 17:37
@benvp I would actually recommend you to utilize the Context for passing state around. Even for interdependencies between states.

```ts
const Todos = () => {
  const root = useRootStore() // or directly React.useContext
  const state = useLocalStore(() => {
    todos: root.initialTodos,
  })
  // use that state directly here, pass through props or setup a separate Context if the tree is deeply nested
}
```

Such an approach gives you much better freedom in my opinion. You can also wrap that into a custom hook for reusability purposes, depends on your needs.

**Comment by spion-h4** [comment] 2019-08-01 15:44
Class based state is great for refactoring existing class-based components that might be using `@observable` state instead of setState. Assuming the component `MyComponent` Its a mechanical refactor:

* you extract the render to a function
* you do `let thisState = useLocalState(props => new MyComponentState(props), props);` at the top
* you replace `this` with `thisState` in the render method
* you rename the old `MyComponent` class into `MyComponentState` and remove "extends React.Component` from it.

**Closed** 2019-08-01 16:15 UTC
Labels: bug, ready for volunteer

**Comment by spion-h4** [comment] 2019-08-02 14:00
Now that this is closed, is this a bug ready for volunteer, already working, or wontfix?

**Comment by FredyC** [comment] 2019-08-02 14:39
@spion-h4 Um, why? There is no logic involved in keeping class based store around, just the following. The `useLocalStore` is meant for **constructing** observable, not for instantiating it.

```jsx
function useClassStore(init) {
  const [store] = React.useState(init)
  return store
}
// and then in a component
const store = useClassStore(() => new RootStore())
```

**Comment by spion-h4** [comment] 2019-08-02 14:46
@FredyC the issue is that the class store needs access to an observable version of the props that autoupdates as new props arrive so it can have computed values (and/or actions) that depend both on the state and the props.
