### ISSUE TITLE
@computed array from map does not update

### ISSUE THREAD

**Issue by AndrewMorsillo** [mobxjs/mobx-react#398] opened 2018-01-25 16:00 UTC
I can't seem to understand why this example does not work

```
class TestStore{
    @observable data = new Map()
    @computed get arr(){ return Array.from(this.data.values())}
    @action.bound addItem(item) { this.data.set(item._id, item) }
}

class data{
    @observable _id: string
    @observable name: string

    constructor(_id, name) {
        this._id = _id
        this.name = name
    }
}

let test = new TestStore()
test.addItem(new data("1", "test1"))
mobx.autorun(() => {
    let myArr = test.arr.map(i => i.name)
    console.log("Myarr is ", myArr)
})
test.addItem(new data("2", "test2"))
```

The only output is `Myarr is ["test1"]`. I expected it to subsequently output "test1", "test2". I have structured my data models in my react app this way and my components are not updating as expected. I expected the `@computed get arr()` to recompute any time an element is added to the observable map.

What am I missing here?

**Comment by mweststrate** [comment] 2018-01-25 16:21
@AndrewMorsillo Two questions (ideally provide a reproduction)

1. does it work if if you use `@computed get arr() { this.data.values() }`?
2. is `Map` polyfilled?

**Comment by AndrewMorsillo** [comment] 2018-01-25 16:31
1. That crashes because .values() returns an iterator, not an array, which does not have a .map function. It does not work if I do `@computed get arr() { observable.array(Array.from(this.data.values()) }` either
2. I'm using webpack/babel/typescript with stage-1 so a polyfill should not be needed

**Comment by mweststrate** [comment] 2018-01-25 19:29
Hmm 1 sounds that your Map is not wrapped into an observable. Are you sure
decorators are transpiled / working?

Op do 25 jan. 2018 om 17:31 schreef amorsillo <notifications@github.com>:

**Comment by mweststrate** [comment] 2018-01-25 19:32
Can you setup a test repo? I think some on a more fundamental level than
Mobx itsel fis going wrong here. If I run your code in a sandbox it works
correct it seems https://codesandbox.io/s/9o1pm6n7kp


Op do 25 jan. 2018 om 20:29 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by AndrewMorsillo** [comment] 2018-01-26 01:21
Interesting, not sure if I will find time to try to make a test repo anytime soon. I'm working around it now by maintaining an observable array alongside of my map instead of using @computed.

**Comment by mweststrate** [comment] 2018-01-26 13:32
Closing for now, until repro is available.

**Closed by mweststrate** 2018-01-26 13:32 UTC

**Comment by AndrewMorsillo** [comment] 2018-01-31 14:32
Here is what my code compiles to in my project

```
var __decorate = undefined && undefined.__decorate || function (decorators, target, key, desc) {
    var c = arguments.length,
        r = c < 3 ? target : desc === null ? desc = (0, _getOwnPropertyDescriptor2.default)(target, key) : desc,
        d;
    if ((typeof Reflect === "undefined" ? "undefined" : (0, _typeof3.default)(Reflect)) === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);else for (var i = decorators.length - 1; i >= 0; i--) {
        if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    }return c > 3 && r && (0, _defineProperty2.default)(target, key, r), r;
};

var TestStore = function () {
    function TestStore() {
        (0, _classCallCheck3.default)(this, TestStore);

        this.data = new _map2.default();
    }

    TestStore.prototype.addItem = function addItem(item) {
        this.data.set(item._id, item);
    };

    (0, _createClass3.default)(TestStore, [{
        key: "arr",
        get: function get() {
            return (0, _from2.default)(this.data.values());
        }
    }]);
    return TestStore;
}();

__decorate([_mobx.observable], TestStore.prototype, "data", void 0);
__decorate([_mobx.computed], TestStore.prototype, "arr", null);
__decorate([_mobx.action.bound], TestStore.prototype, "addItem", null);

var data = function data(_id, name) {
    (0, _classCallCheck3.default)(this, data);

    this._id = _id;
    this.name = name;
};

__decorate([_mobx.observable], data.prototype, "_id", void 0);
__decorate([_mobx.observable], data.prototype, "name", void 0);
var test = new TestStore();
test.addItem(new data("1", "test1"));
mobx.autorun(function () {
    var myArr = test.arr.map(function (i) {
        return i.name;
    });
    console.log("Myarr is ", myArr);
});
test.addItem(new data("2", "test2"));
```


If I change ```@observable data = new Map()``` to ```data = observable.map()``` my example works correctly. Not sure what is going wrong with the @observable decorator here. All other observable decorators work fine in my project, it only appears to be map that does not work correctly.

**Comment by tur-nr** [comment] 2019-05-01 07:33
This is happening to me, I found out that because of `core-js` polyfill on collections (maps and sets) that mobx doesn't identify it as a valid Map object.

https://github.com/mobxjs/mobx/blob/master/src/utils/utils.ts#L146

So what's happening is your code is getting compiled and using the ES6 polyfilled constructor from the `core-js` library. So when you create a `new Map` what you're actually doing is `new PolyfilledMap`. Now mobx checks to see if you are a map instance so it can merge the data into the new observable using the util function above. However, because your babel (I presume) doesn't compile vendor libraries such as mobx it is actually referencing the native browser `Map`, so the `instanceof` check fails.

Not sure where to go with this myself as it's not really mobx's concern. I think there must be a way to disable `core-js` from polyfilling I just haven't found out how to. No matter if I set my `babel-preset-env` to target `last Chrome version`, somehow it still adds it 😕

**Comment by ditiem** [comment] 2019-12-07 00:20
I think I am having the same or very similar problem.

[Here is the test code](https://codesandbox.io/s/agentsh-demo-2-fxy8l?fontsize=14&hidenavigation=1&theme=dark)

In case there is a problem with the link, here is the code:

```
import {observable, computed, action, reaction} from "mobx" 

class TestStore{
    data = observable.map( )
    
    @computed get arr()
    { return Array.from(this.data.values())}

    @action.bound addItem(item) 
    { this.data.set(item._id, item) }
}

let test = new TestStore()
test.addItem({ _id: 1, name: "test1" })
reaction( 
  () => JSON.stringify( test.arr )
, ( arr ) => console.log("Myarr is ", arr)
) ;
test.data.replace([ [2,{_id: 2, name: "test2"}] ] )
```

Basically, the reaction is not called.

**Comment by FredyC** [comment] 2019-12-07 07:37
Please, refrain from commenting on old and closed issues as only a few people will see that. Open new issue with all necessary details.
