### ISSUE TITLE
observableRequiresReaction + mobx-react = Observable reactive state being read outside a reactive context 

### ISSUE THREAD

**Issue by GongT** [mobxjs/mobx-react#806] opened 2019-12-06 10:16 UTC
```typescript
import { render as renderDom } from 'react-dom';
import * as React from 'react';
import { observer } from 'mobx-react';
import { observable, configure, action, reaction } from 'mobx';

configure({
	computedRequiresReaction: true,
	observableRequiresReaction: true,
	reactionRequiresObservable: true,
	enforceActions: 'observed',
});

const globalStateInAnotherFile = observable({
	counter: 0,
});

@observer  /// <--------- THIS
class SimpleTest extends React.Component<any> {
	render() {
		return (
			<React.Fragment>
				<h1>{globalStateInAnotherFile.counter}</h1>
				<button onClick={() => this.testAction()}>i++</button>
			</React.Fragment>
		);
	}

	@action
	testAction() {
		globalStateInAnotherFile.counter++;
	}
}

reaction(
	() => globalStateInAnotherFile.counter,
	(v) => console.log('current value is %d', v)
);

renderDom(<SimpleTest />, document.getElementById('applicationRoot'));
```

On page render, console warn this 8 times:
```text
[mobx] Observable reactive state being read outside a reactive context 
    in SimpleTest
```

call stack show 5 different place causing the warning. all comes from `react-dom.development.js`, like:
* constructClassInstance: `var state = workInProgress.memoizedState = instance.state !== null && instance.state !== undefined ? instance.state : null;`
* checkClassInstance: `var _state = instance.state;`
* updateClassComponent: `if (inst.props !== nextProps) {`

Whenever I click the button, log:
```text
current value is 6
[mobx] Observable reactive state being read outside a reactive context 
    in SimpleTest
[mobx] Observable reactive props being read outside a reactive context 
    in SimpleTest
```

I can't fix this by reading the doc. Please help.

**Comment by FredyC** [comment] 2019-12-06 10:18
Would you mind moving that code to CodeSandbox so we can see it action?

**Comment by GongT** [comment] 2019-12-06 11:08
@FredyC 
[![Edit nifty-oskar-o5xyd](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-oskar-o5xyd?fontsize=14&hidenavigation=1&theme=dark)

**Comment by FredyC** [comment] 2019-12-06 12:03
@Bnaya @urugator Can you have a look, please?

**Comment by Bnaya** [comment] 2019-12-06 13:03
this is probably related to https://github.com/mobxjs/mobx/issues/2195, a fix has been merged, waiting to be released

**Comment by Bnaya** [comment] 2019-12-06 13:16
After some debugging - it's not related.

The problem is:
`makeObservableProp(target, "state")` turn state into observable, and react is internally accessing instance.state after component creation Not only inside render().

**Comment by Bnaya** [comment] 2019-12-06 13:18
https://github.com/mobxjs/mobx-react/blob/master/src/observerClass.js#L25-L30

**Comment by Bnaya** [comment] 2019-12-06 13:28
A possible fix from mobx side:
We can add a feature to also configure/override `observableRequiresReaction` per observable (in a similar manner to computedRequiresReaction flag per reaction) and mobx-react will use it

We are probably not going to make props & state not observable i guess:)

**Comment by urugator** [comment] 2019-12-08 17:21
We could `mobx._allowStateReads` around `getAtom.call(this).reportObserved()` inside the getter
https://github.com/mobxjs/mobx-react/blob/78c6b4964c7703de7a673913d759e9a2aab669f3/src/observerClass.js#L140-L143

> why can't it be only the content of instance.state 

It's to make the following work:
```javascript
@computed get thing() {  
  return this.state.thing; // usually it's props/state combined with something observable
  // or with props
  return this.props.thing;  
}
// similary reaction/autorun
```

Configurable observables fields are problematic due to the syntax/overloading.

**Comment by Bnaya** [comment] 2019-12-08 17:35
So you say we expose allowStateReads as public api from the the mobx package, in a similar manner to `_startAction/_endAction`?

**Comment by urugator** [comment] 2019-12-08 20:23
Yes, iirc `_allowStateChanges` is also exposed...

**Comment by GongT** [comment] 2019-12-10 07:32
@Bnaya 

should "disable state/props observable" be a new option?

**Comment by Bnaya** [comment] 2019-12-12 09:38
@GongT that's also an idea if @FredyC see fit
But we will also do the `_allowStateReads` thing anyhow.

**Comment by FredyC** [comment] 2019-12-12 10:10
I am not entirely sure what option to add where? The `observer` does not allow for any options really.

**Comment by urugator** [comment] 2019-12-12 11:06
One can keep the field private and expose it via getter wrapped in `_allowStateReadsStart/End`.
It's really an edge atm, no need to complicate the code and clutter API.
Btw there is other way to fix this ... do you remeber the discussion whether we should place the checking into `reportObserved` or rather into individual accessors? If we would place it into individual accessors, it wouldn't perform the check for custom Atoms... (similary as `allowStateChanges` is ignored) ... 
However this could be considered a flaw, especially when `checkIfStateChanges/ReadsAreAllowed` is not exposed, so there is no way to impelement this checking on custom atoms even by hand...

**Comment by mweststrate** [comment] 2019-12-12 11:09
Exposing the last ones for lib authors should be fine imho (prefixed with _)

**Comment by Bnaya** [comment] 2019-12-23 20:35
_allowStateReadsStart/End has been published in mobx,
So the proposed fix can now be published

**Comment by sammy007** [comment] 2020-02-06 08:30
So if there is `<Input value={this.someValue} onChange={this.handleChange}/>` and this `someValue` is observable, `handleChange` is an `action.bound` and the component itself is `observer`, but `Input` is not an observer it's considered `not idiomatic` (let's assume for a moment that whole javascript thing is not a disgusting pile of junk)? So the solution is to add a dozen of crutches, overload already overloaded with that metaprogramming junk component just to make mobx checker happy?

**Comment by mweststrate** [comment] 2020-02-06 09:22
@Bnaya would you mind creating a PR for this? it hasn't been implemented yet, correct? Or did I miss it?

@sammy007 sorry, I don't get what your comment is about or what would be non idiomatic about what you are proposing, but please open a fresh issue rather than commenting at seemingly unrelated issues.

**Comment by sammy007** [comment] 2020-02-06 09:39
Everything is related here, getting tons of `Observable reactive state being read outside a reactive context`, added:

```jsx
render() {
            return (
                <Observer
                    render={() => (
                      <Form.Control type="text" value={...} ...
```

it's silent now. Why all that junk needed? It works without that strict checks anyway.

**Comment by mweststrate** [comment] 2020-02-06 09:45
That sounds like you are not leveraging observability at all and could just as well have used a plain value, or should be passing a plain value down. To further please open a fresh issue including a small reproduction. Same symptoms !== same issue.

**Comment by sammy007** [comment] 2020-02-06 09:54
@mweststrate  https://github.com/mobxjs/mobx-react/issues/828

**Closed** 2020-02-06 14:10 UTC
Labels: bug
