### ISSUE TITLE
component does not re-render

### ISSUE THREAD

**Issue by rehat101** [mobxjs/mobx-react#626] opened 2018-12-15 10:28 UTC
I have a component that renders a list of grid items from an observable array and these items render just fine on `componentDidMount()` 

I have another component in parallel that parses, uploads a file, and triggers a store action which sets the same observable array above.

However, after the trigger the grid items doesn't seem to re-render. 

`Grid.js`

```
@inject('GridStore')
@observer
class Grid extends Component {

	constructor(props) {
		super(props);
	}

	async componentDidMount() {
		const { GridStore } = this.props;
		await GridStore.loadData();

		console.log('MOUNTED', GridStore.data[0]._source.artboard_name);
	}

	componentDidUpdate() {
		const { GridStore } = this.props;

		console.log('UPDATED', GridStore.data[0]._source.artboard_name);
	}

	render() {
		const { GridStore } = this.props;
		let data = GridStore.data;
		return(
			<div>
				<GridList artboards={data}/>
			</div>
		)
	}
}

class GridList extends Component {
	render() {
		const { artboards } = this.props;
		return(
			<GridWrapper>
				{artboards.map((d,i) =>
					<GridItem key={d._id}>
						<GridItemInner>
							<LazyImg src={d._source.artboard_image_url}/>
						</GridItemInner>
					</GridItem>
				)}
			</GridWrapper>
		);
	}
}

```

`Upload.js`

```
@inject('UploadStore', 'AppStore', 'GridStore')
@observer
class Upload extends Component {

	constructor(props) {
		super(props);

		this.handleFile = this.handleFile.bind(this);
	}

	async handleFile(acceptedFiles) {
		const { UploadStore, AppStore, GridStore } = this.props;
		const file = acceptedFiles[0];

		let formData = new FormData();
		formData.append("sketchFile", file, file.name);

		AppStore.setIsLoading(true);
		let response = await UploadStore.uploadFile(formData);
		await GridStore.loadData()
		AppStore.setIsLoading(false);

		if(response.status == 400) {
			console.error( await response.text() );
		}

	}

	render() {
		return(
			<UploadWrapper>
				<Dropzone
					accept=".sketch"
					onDrop={this.handleFile}
					name="sketchFile"
					className="dropzone">
				<UploadIcon/>
				</Dropzone>
			</UploadWrapper>
		)
	}
}
```

On mobx's site in the performance section it suggests to break the lists down and that's what I did on my Grid component but I still have to manually refresh the browser to see the change in the grid items.

**Comment by mweststrate** [comment] 2018-12-15 11:55
Note that @autobind might be in the way

Op za 15 dec. 2018 11:28 schreef Taher <notifications@github.com>:

**Comment by rehat101** [comment] 2018-12-15 15:13
@mweststrate autobind inside `Upload.js` ? If I remove it there I get a TypeError below: 

`Uncaught (in promise) TypeError: Cannot read property 'setIsLoading' of undefined`

**Comment by rehat101** [comment] 2018-12-15 16:05
@mweststrate If I remove autobind in Upload.js and try it my this doesn't get bounded to the class - I have to bind it somehow. I tried binding it manually in the constructor which also doesn't trigger the component to re-render.

**Comment by rehat101** [comment] 2018-12-16 01:41
I added the following log inside `componentDidUpdate` to check whether the values are updating and it's not until I manually refresh the page.

I have also removed autobind

```async componentDidMount() {
		const { GridStore } = this.props;
		await GridStore.loadData();

		console.log('MOUNTED', GridStore.data[0]._source.artboard_name);
	}

	componentDidUpdate() {
		const { GridStore } = this.props;

		console.log('UPDATED', GridStore.data[0]._source.artboard_name);
	}
```

**Comment by rehat101** [comment] 2018-12-16 02:39
I have also happen to find if I delay reloading the observable data, my grid component DOES re-render with new values!

I'm not sure what's going on here though? 

```
if(response.status == 200) {
	await Promise.delay(4000);
	await GridStore.loadData();
}
```

**Comment by ItamarShDev** [comment] 2018-12-16 21:18
can you please attach a code link to code-sandbox?

**Comment by rehat101** [comment] 2018-12-17 14:09
@ItamarShDev since my usecase is related to async calls it might be very hard to port it to a sandbox. Do you suggest an alternative?

**Comment by mweststrate** [comment] 2018-12-18 08:48
@rehat101 porting isolated case shouldn't be hard. You can stub calls by creating a promise and resolving with some hardcoded json, that simulates async well enough

**Comment by realfresh** [comment] 2018-12-23 03:55
Hey guys, just wanted to chime in. I was literally smashing my head against the wall with an issue that may be related to yours. I feel others may stumble here looking for a solution as well.

For some reason, my component (which was injected, observed and autobinded) if rendered the first time initially worked fine. However, if a user navigated away and the component was destroyed, the next time it is rendered again, all subsequent updates to the component either via props or state stopped working.

Here is the real gotcha though, if you are using HMR, the issue will be masked in development and everything will work fine. However, once you run the production build, it no longer works correctly since HMR is no longer enabled. I have 100% confirmed this.

Eventually pulling autobind from the component make it function properly after.

**Comment by mweststrate** [comment] 2018-12-28 16:19
Closing for inactivity

**Closed by mweststrate** 2018-12-28 16:19 UTC
