### ISSUE TITLE
Better typescript declarations for inject

### ISSUE THREAD

**Issue by Bnaya** [mobxjs/mobx-react#303] opened 2017-07-25 12:39 UTC
Currently, when you you use `inject` the returned wrapper component still requires the same props as the wrapped component.

The advised solution is to mark the to-be injected  props as optional, but with strict null check its very cumbersome to use. and also make the decelerations not accurate.

My local solution is this component: 

```ts
import { inject, IReactComponent } from "mobx-react";

function mobxInject<newProps, oldProps extends newProps>(
  stores: string[],
  wrappedComponent: IReactComponent<oldProps>,
) {
  return inject.apply(null, stores)(wrappedComponent) as IReactComponent<newProps>;
}

export default mobxInject;
```

That you need to specify the props that left after the inject.
it looks pretty verbose right now, but maybe it possible to make it more compact

**Comment by mweststrate** [comment] 2017-07-25 13:34
Duplicate of https://github.com/mobxjs/mobx-react/issues/256

**Closed by mweststrate** 2017-07-25 13:34 UTC
