### ISSUE TITLE
'componentWillReact' of undefined after updating to 6.1.0.

### ISSUE THREAD

**Issue by hh83917** [mobxjs/mobx-react#709] opened 2019-06-19 17:37 UTC
Due to the recent `componentDidUpdate` bug in mobx-react v6 we tried to upgrade to 6.1.0 but the page doesn't load and got this in the console.

```
vendors.bundle.a88a35b9.js:145824 Uncaught TypeError: Cannot read property 'componentWillReact' of undefined
```

"mobx": "^4.5.0",
"mobx-react": "^6.1.0"

Tried updating mobx to 4.11.0 and mobx-react to 6.1.1 doesn't fix it either.

**Comment by FredyC** [comment] 2019-06-19 18:48
I assume you don't use `componentWillReact` in your code? Well, there is the only occurrence of it here...

https://github.com/mobxjs/mobx-react/blob/78216feb36ec5398a0b800092677c81cc75d2beb/src/observerClass.js#L14

That would effectively mean you have tried to call `observer` on something that's undefined. Could be caused by circular dependency, hard to guess without an actual code.

Either way, we should guard against it and produce some better error message.

**Comment by hh83917** [comment] 2019-06-19 21:12
Thanks @FredyC for the tip! `...tried to call observer on something that does not have a prototype`.

I found someone did this on some of the functional components:

```
const SomeComponent observer(() => {
	...etc.
})

export default observer(SomeComponent)
```

Good thing it breaks so we got that syntax thing fixed, someone (gitblame... 😛) may have missed it during refactor from class component.

**Comment by FredyC** [comment] 2019-06-20 07:11
Glad I could help.

I will keep this open as we shall provide better handling of such error. The error you encountered is definitely way too cryptic.

**Comment by mweststrate** [comment] 2019-06-20 07:37
@hh83917 could you give us the actual component definition that was wrong? That will help us in creating a reproduction (all the methods can be empty, it is just about the structure your code was in)

**Comment by FredyC** [comment] 2019-06-20 07:52
@mweststrate He already did, here is the repro... https://codesandbox.io/s/shy-monad-2d4up

**Comment by hh83917** [comment] 2019-06-20 08:25
@FredyC @mweststrate Thanks for following up on the issue and @FredyC for creating that sand box for me as reference for better error messages.

As @FredyC pointed out, we are not using `componentWillReact` in our codebase, so the error message definitely comes as cryptic. Also, we were originally on `6.0.3` and the page still renders with double `observer`s in couple places in some older  codes. Was not expecting breaking change when upgrading to `6.1.0`.

**Comment by ConneXNL** [comment] 2019-06-25 11:07
I just got this when I accidentally used React.memo and observer at the same time:
observer(React.memo((props) => <span>test<span>)))

**Comment by anoopmd** [comment] 2019-07-09 20:33
I got the same error. Rolled back to 5.4.4 and its working fine in the older version.

**Comment by FredyC** [comment] 2019-07-09 21:18
@anoopmd Thanks for the reminder, forgot about a pending PR. Just merged so it should be fixed in the next V6 release.

**Closed** 2019-07-09 21:17 UTC
Labels: bug, hasPR

**Comment by johnnyreilly** [comment] 2019-07-27 13:35
> I just got this when I accidentally used React.memo and observer at the same time:
observer(React.memo((props) => test)))

@ConneXNL thanks for sharing that - I just bumped on this too.

Would someone be able to provide an explanation of why you can't mix `React.memo` and `observer` please?  I'd love to give a good explanation to the team (and understand myself 😄 )

**Comment by FredyC** [comment] 2019-07-27 14:40
Well, observer pack `React.memo` underneath, so there is no need to use it (only by accident). Why it's a problem to have it there twice it's probably more of the question for a React team :)

**Comment by FredyC** [comment] 2019-08-08 11:44
6.1.2 published with this fix

**Comment by jstansbe** [comment] 2019-08-08 19:07
"Cannot read property ' componentWillReact' of undefined"

    "mobx": "^5.13.0",
    "mobx-react": "^6.1.2",
    "mobx-state-tree": "^3.14.1",
    "react": "16.8.6",
    "react-native": "0.60.4",

**Comment by FredyC** [comment] 2019-08-08 19:50
@jstansbe Can you provide reproduction, please? Might be some other case we have missed there.

**Comment by andq-ibl** [comment] 2019-08-19 09:11
I'm using :
```
"node":v10.13.0,
"react": "^16.8.4",
"mobx": "^5.13.0",
"mobx-react": "^6.1.3",
```
Got the same issue but I do not use react.memo. I checked the code and make some log:
![Screen Shot 2019-08-19 at 4 08 00 PM](https://user-images.githubusercontent.com/29767799/63253299-c6a60800-c29b-11e9-8e5e-b4615b6c0a08.png)

And the result I got is like this:
<img width="796" alt="Screen Shot 2019-08-19 at 4 10 37 PM" src="https://user-images.githubusercontent.com/29767799/63253383-f5bc7980-c29b-11e9-8a87-d0563d79fe20.png">

After changing  `t=e.prototype` to `t=e.__proto__`, it's worked

**Comment by FredyC** [comment] 2019-08-19 09:35
@andq-ibl Once again, without reproduction, it's not possible to fix it.

And I am going to lock this, it's clearly some other issue so let's treat it like that.
