### ISSUE TITLE
observer component may stop reacting to observable changes if `shouldComponentUpdate` prevent render

### ISSUE THREAD

**Issue by gbiryukov** [mobxjs/mobx-react#417] opened 2018-02-08 17:47 UTC
First of all thanks guys for awesome work, I ❤️ mobx 😊

I think I found edge case with bug, there is jsfiddle demonstrating the issue https://jsfiddle.net/ry8on8u6/54/
In this example person name change (caused by timer) will not be reflected in component.

Explanation
---

mobx-react report observable props change [when detect shallow change in props](https://github.com/mobxjs/mobx-react/blob/master/src/observer.js#L151).

That turns reaction that re-render component into stale state. mobx-react expect that shalow props change should lead to component re-render, and it will reset reaction state back to up to date.

But what will happen if component render will be prevented by `shouldComponentUpdate`?
It may happen if it has logic preventing render even in case of shallow changes.

In this case reaction will preserve stale state and [will not be executed](https://github.com/mobxjs/mobx/blob/master/src/core/observable.ts#L192) even if its observables will change.

This is relevant for react 16, mobx 3.4.1, mobx-react 4.3.5.

Solution
---

Right now I have no idea how to fix it in mobx-react so I changed my sCU for one particular case. 
But anyone may face the same and spend a lot of time to understand what is going on.

Do you have any ideas how to fix it in mobx-react?

**Comment by jraoult** [comment] 2018-03-28 18:35
@gbiryukov I ran into the same issue today. Have you made any progress and found the root cause?

**Comment by mweststrate** [comment] 2018-03-28 19:48
Please don't implement shouldComponentUpdate on observer components. The
whole point of observer is to do that for you, and overriding that behavior
will just make everybodies head hurt :). Split into two components or use
Observer sections instead of observer decorator if you want fine grained
sCU control for some not mobx related pieces of data.

Op wo 28 mrt. 2018 om 20:35 schreef Jonathan Raoult <
notifications@github.com>:

**Comment by jraoult** [comment] 2018-03-28 19:56
Thanks @mweststrate for your reply. I agree with you about that :) That said it is documented and I was expecting to work without issue (cf https://github.com/mobxjs/mobx-react#about-shouldcomponentupdate). To understand better, are you saying this is not a bug?

**Comment by gbiryukov** [comment] 2018-03-28 20:48
The issue is that you even might doesn't know that particular component has `shouldComponentUpdate` defined when wrapping third-party component into `observer` (my case). So to understand the issue you have to debug why some library-provided component doesn't work with mobx.

Maybe it will make sense to add warning when `observer` detect predefined `shouldComponentUpdate` on passed Component?

**Comment by mweststrate** [comment] 2018-03-28 21:02
Eh don't wrap third party components in observer if they aren't designed
for that...

Op wo 28 mrt. 2018 22:49 schreef George <notifications@github.com>:

**Comment by mweststrate** [comment] 2018-04-30 18:44
@jraoult updated the readme to clarify it better. Closing the issue. 

@gbiryukov if your question is still open, please open a new issue or search for info about third-party components. But the tl;dr; is: don't make 3th party components observer, and don't pass them observables. If third part components takes render callbacks or something similar, you probably want to make those callbacks `observer` / `Observer`

**Closed by mweststrate** 2018-04-30 18:44 UTC
