### ISSUE TITLE
@inject with jest test issue

### ISSUE THREAD

**Issue by rssole** [mobxjs/mobx-react#357] opened 2017-11-07 11:03 UTC
Hi I have some test which is run by jest, and it is quite simple:

```
it('renders each verify response', () => {
    const gridWrapper = mount(&lt;ResponseGrid advStore={aStore}/&gt;);

    expect(gridWrapper.find(Row)).toHaveLength(1);
  });
```

ResponseGrid is quite simple with just 

```
export interface ResponseGridProps {
  advStore?: ADVStore;
}

@inject(allStores => ({
  advStore: allStores.advStore as ADVStore
}))
class ResponseGrid extends React.Component<ResponseGridProps, {}> {

  constructor(props) {
    super(props);
  }

  public render() {
    const rows = this.props.advStore.data.map((pvr, i: number) => <Row key={i}/>);
   ... rest ommitted...

```
Now I have issue that `render` fails becuse `this.props.advStore` is undefined in given setup.
Now, 
if I comment out @inject from component - it works as it is above.
if I take back @inject and in test I wrap my component in `<Provider>` - it works

I am using mobx-react 4.2.2.

Now, as per docs, it should work as given above without wrapping in `<Provider> ` by just specifying
property directly. 
However given above to me it seems that @inject overwrites my prop with null/undefined if it 
is not provided.

Any hint/tip/suggestion is welcome and appreciated.

**Comment by mweststrate** [comment] 2017-12-05 13:00
@rssole is the `advStore` null in the outermost component under test, or in some deeper component? Prop injection should work, but only for the outermost component. if there is inject somewhere deeper in the tree it won't pick it up.

**Comment by mweststrate** [comment] 2017-12-05 13:45
This seems to be a duplicate of #260. Please reopen if it isn't

**Closed by mweststrate** 2017-12-05 13:45 UTC
