### ISSUE TITLE
Problem with version 6.3.0 and mobx v5

### ISSUE THREAD

**Issue by eloim-zubkov** [mobxjs/mobx-react#898] opened 2020-10-01 08:03 UTC
## Actual outcome
WARNING in ./node_modules/mobx-react-lite/es/utils/assertEnvironment.js 6:5-19
"export 'makeObservable' was not found in 'mobx'

## Versions
"react": "16.9.0",
"mobx": "5.15.4",
"mobx-react": "6.3.0",

**Comment by FredyC** [comment] 2020-10-01 08:08
6.3.0 requires mobx v6. It's declared in peerDependencies.

@mweststrate Perhaps it might be worth releasing mobx-react@7 so people don't fall into this accidentally and then have to follow through a "painful" upgrade loop?

**Comment by eloim-zubkov** [comment] 2020-10-01 08:10
6.3.0 requires mobx v5, not 6
https://github.com/mobxjs/mobx-react/blob/6.3.0/package.json#L45

**Comment by FredyC** [comment] 2020-10-01 08:18
Ok sorry, I looked to the master branch assuming it's the latest.

https://github.com/mobxjs/mobx-react/blob/9b5d61c10f0876b67ab39270b586a7b3f6ace6e4/package.json#L45

So it seems you have mobx-react-lite@3 installed for some reason?

**Comment by eloim-zubkov** [comment] 2020-10-01 08:20
yeap
but mistake is over here
https://github.com/mobxjs/mobx-react/blob/6.3.0/package.json#L93
it's automatically install mobx-react-lite v3

**Comment by FredyC** [comment] 2020-10-01 08:24
I see you are right, that was clearly an oversight. Should be something like `>=2.2.0 <3`.

I guess we will have to unpublish 6.3.0 and publish 7.0 instead just make it more clear.

**Comment by mweststrate** [comment] 2020-10-01 08:28
Duplicate of #897, please upgrade to 6.3.1

**Closed by mweststrate** 2020-10-01 08:28 UTC
Labels: discuss

**Comment by FredyC** [comment] 2020-10-01 08:29
Just wanted to say the same thing :) I've just deprecated 6.3.0 with the message "Please use 6.3.1 instead of this version".

**Comment by mweststrate** [comment] 2020-10-01 08:30
hmm the dist tag of latest is wrong though, let me see if that can be fixed

**Comment by FredyC** [comment] 2020-10-01 08:31
![image](https://user-images.githubusercontent.com/1096340/94786482-52f88900-03d1-11eb-920d-2a4d9a1c7a96.png)

I see it fine

**Comment by mweststrate** [comment] 2020-10-01 08:32
No, `latest` should be 7.0.0 which has already released. Should be fixed now but might take a bit to propagate

```
npm dist-tags add mobx-react@7.0.0 latest
+latest: mobx-react@7.0.0
```

**Comment by eloim-zubkov** [comment] 2020-10-01 13:30
> Duplicate of #897, please upgrade to 6.3.1

I can't upgrade to 6.3.1 because I can't upgrade mobx to v6. Not all libraries support mobx v6.
Also I can't downgrade to 6.2.5
Could you add this fix?
> I see you are right, that was clearly an oversight. Should be something like >=2.2.0 <3.

**Comment by mweststrate** [comment] 2020-10-01 13:32
@eloim-zubkov mobx-react@6.3.1, not mobx@6.3.1. Those version number are unrelated.
