### ISSUE TITLE
Observer TS error for stateless component

### ISSUE THREAD

**Issue by joevo2** [mobxjs/mobx-react#267] opened 2017-05-31 09:58 UTC
When i do this `const TodoView = observer(({todo}) => <div>{todo.title}</div>)`

I just get this.... need help on this TS error
```
error TS2459: Type '{ children?: ReactNode; }' has no property 'todo' and no string index signature.
```

**Comment by mweststrate** [comment] 2017-07-11 13:18
Is this still an issue? If so can you set up a reproduction in a fiddle (with TS) or small test project?

**Comment by kresli** [comment] 2017-10-07 14:18
I hit on the same issue. Actually its not an issue because typing is missing. In my case 
```
const InputLabel: React.ClassicComponentClass<{label: string | undefined}> = observer(({label}) => {
  return label && <Label>{label}</Label> || null;
});
```

**Comment by mweststrate** [comment] 2017-12-05 13:39
Typings have been improved a lot lately, please reopen if the issue isn't resolved in the latest verions

**Closed by mweststrate** 2017-12-05 13:39 UTC
